### PR TITLE
JRuby CI

### PR DESCRIPTION
**Pull request by tamird**
@saghaulor

### CODE REVIEW

**Comment by tamird** [comment]
@saghaulor green

**Comment by tamird** [comment]
cc @headius some strange JRuby issues here. I've done my best to follow guidance on https://github.com/jruby/jruby/wiki/UnlimitedStrengthCrypto but still seeing issues with certain ciphers. Minimal repro below:

```
~/Development/encryptor jruby rvm jruby do ruby jruby_crypto.rb
OpenSSL::Cipher::CipherError: java.security.InvalidKeyException: key size must be 16 or 24 bytes.: possibly you need to install Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files for your JRE
  update at org/jruby/ext/openssl/Cipher.java:1086
  (root) at jruby_crypto.rb:8
~/Development/encryptor jruby cat jruby_crypto.rb
require 'openssl'
require 'securerandom'

cipher = OpenSSL::Cipher::Cipher.new('des-ede')
cipher.encrypt
cipher.iv = SecureRandom.random_bytes(24)
cipher.key = SecureRandom.random_bytes(24)
result = cipher.update(SecureRandom.random_bytes(64))
result << cipher.final
```

**Comment by tamird** [comment]
related:
* https://github.com/jruby/jruby/issues/2617
* https://github.com/jruby/jruby-openssl/issues/31

**Comment by saghaulor** [comment]
@tamird I cherry picked your work into my branch as it was related. It was merged with my pull request https://github.com/attr-encrypted/encryptor/pull/16 Thanks for your help!

**Comment by headius** [comment]
Anything more you need from me here?

**Comment by tamird** [comment]
@headius the JRuby issues are tracked in
https://github.com/jruby/jruby-openssl/issues/31. An update there would be
most welcome.

**Pull request closed without merging**
